### ISSUE TITLE
Cannot find fun in GCC

### ISSUE THREAD

**Issue by antoniwalburg** [KrasowskiMarcin/projekt#1]
Hello, I'm having trouble in finding fun in GCC. What can i do to resolve it?

**Comment by antoniwalburg** [comment]
Hell YEAH!

**Comment by KrasowskiMarcin** [comment]
Hello, that's simply because you are a white man. 
Closing this thread rn and marking as resolved

**Comment by antoniwalburg** [comment]
Okey!
